# Generated by Django 5.2.16 on 2026-09-09 20:54

import django.core.validators
import django.db.models.deletion
import redacoes.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Redacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='tema')),
                ('imagem', models.ImageField(blank=True, upload_to='redacoes/%Y/%m/', validators=[redacoes.validators.validar_tamanho_imagem], verbose_name='imagem da redação')),
                ('texto_original', models.TextField(blank=True, verbose_name='texto original')),
                ('texto_transcrito', models.TextField(blank=True, verbose_name='texto transcrito')),
                ('texto_revisado', models.TextField(blank=True, verbose_name='texto revisado')),
                ('resultado_json', models.JSONField(blank=True, default=dict, verbose_name='resultado estruturado')),
                ('status', models.CharField(choices=[('enviada', 'Enviada'), ('processando', 'Processando'), ('concluida', 'Concluída'), ('erro', 'Erro')], db_index=True, default='enviada', max_length=20, verbose_name='status')),
                ('comentario_professor', models.TextField(blank=True, verbose_name='comentário do professor')),
                ('corrigido_em', models.DateTimeField(blank=True, null=True, verbose_name='corrigido em')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('atualizada_em', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redacoes', to=settings.AUTH_USER_MODEL, verbose_name='aluno')),
                ('corrigido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redacoes_corrigidas', to=settings.AUTH_USER_MODEL, verbose_name='corrigido por')),
            ],
            options={
                'verbose_name': 'redação',
                'verbose_name_plural': 'redações',
                'ordering': ['-criada_em'],
            },
        ),
    ]
