# Generated by Django 5.2.16 on 2026-07-30 20:38

import django.core.validators
import redacoes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='tema')),
                ('imagem', models.ImageField(blank=True, upload_to='redacoes/%Y/%m/', validators=[redacoes.validators.validar_tamanho_imagem], verbose_name='imagem da redação')),
                ('texto_original', models.TextField(blank=True, verbose_name='texto original')),
                ('texto_transcrito', models.TextField(blank=True, verbose_name='texto transcrito')),
                ('texto_revisado', models.TextField(blank=True, verbose_name='texto revisado')),
                ('resultado_json', models.JSONField(blank=True, default=dict, verbose_name='resultado estruturado')),
                ('status', models.CharField(choices=[('enviada', 'Enviada'), ('processando', 'Processando'), ('concluida', 'Concluída'), ('erro', 'Erro')], db_index=True, default='enviada', max_length=20, verbose_name='status')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('atualizada_em', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
            ],
            options={
                'verbose_name': 'redação',
                'verbose_name_plural': 'redações',
                'ordering': ['-criada_em'],
            },
        ),
    ]
